### ISSUE TITLE
bug on load and project url update

### ISSUE THREAD

**Issue by acehaddock** [carfup/XTBPlugins.PersonalViewsMigration#18]
once connected to XRM toolbox and then connected to my Env.  when I lick to open the Peronsl user views migration tool i get the below error

![image](https://user-images.githubusercontent.com/24735301/57477117-347e7480-7255-11e9-8f87-b9e6f7878ae3.png)

also i noticed the project url is goign to delta assemblyvscrm should it not go to xtbPlugins.personalviewsmigration ?

thanks

**Comment by carfup** [comment]
Hi,

Thanks for your feedback.
Regarding the project url, my bad, i guess it's a bad copy/paste, will be fixed within the next release.

For the error, can you give me "more" context, such as : xtb version, plugin version, did you have this error before ? are you using an online or onpremise environment ? Any particular clicks to get it ?

Clément

**Comment by carfup** [comment]
Can you try that fix : https://we.tl/t-GMXyCdTkov ?

And let me know if this is better now ?

Thanks

**Comment by simes1** [comment]
I have the same problem.

XRMToolbox: v1.2019.6.33

This Plug-in: v1.2019.5.7

**Comment by simes1** [comment]
This appears to be because this plug-in (and a whole load of others) don't appear to have been updated for the latest version of XRMToolbox:

https://github.com/MscrmTools/XrmToolBox/issues/868

**Comment by carfup** [comment]
Hello Simes1,
I'm aware of this issue and will publish a fix later this week. 
I keep you posted.

**Comment by simes1** [comment]
Thanks

**Comment by carfup** [comment]
Hey,

Can you try that version : https://github.com/carfup/XTBPlugins.PersonalViewsMigration/releases/tag/1.2019.6.8-beta ?

It should fix it

**Comment by simes1** [comment]
I've rolled back XRMToolbox to a previous version because so many of the plugins I have been trying to use appear to suffer the same problem.  When I get a chance I'll see if I can get the latest version working somewhere else and see if I can figure out how I get it to use this beta version of your plugin instead of the published one.

**Comment by simes1** [comment]
Hi Clement,

Just to let you know that I finally figured out how to use your beta version with the updated version of XRMToolBox whilst still maintaining the old one along side.

Your new version appears to work (although I've not tried actually assigning Copying, Assigning or Deleting anything yet).

I particularly like the fact that it now handles Team owned as well as User owned artefacts (something a lot of the other tools cannot do yet).

My next ask (I'm sure it's on your list) is to be able to modify the sharing

**Comment by carfup** [comment]
Hello,

I just published the new version of the plugin which fix the initial error of this issue.

@simes1 do not hesitate to create an other issue for the edition of the sharings (i can check that later on!)

thanks to both of you.
ref #21
