### ISSUE TITLE
Ability to modify sharing

### ISSUE THREAD

**Issue by simes1** [carfup/XTBPlugins.PersonalViewsMigration#22]
As discussed in an earlier issue it would be great to be able to edit the sharing of the Views, Charts and Dashboards with both Users and Teams.  It would be even better to be able to do this in bulk.

When copying it would be great to copy with or without the sharing

**Comment by carfup** [comment]
Hi Simes1,

It's not the complete requirement but with the latest version 1.2019.9.9 you can copy a view/dashboard/chart with or without the sharings!

**Comment by carfup** [comment]
Hi @simes1 ,

i'm happy to announce that your wish is now real, you can now edit sharings from the app ! #34 

Enjoy !
