### ISSUE TITLE
More than 5000 users isn't working

### ISSUE THREAD

**Issue by seanmcne** [carfup/XTBPlugins.PersonalViewsMigration#23]
We have about 15,000 users in our system and it appears to only be loading a smaller number (most likely 5000).

**Comment by carfup** [comment]
Hello Sean,

Indeed, my bad here, i will fix that !

Clément

**Comment by ovinophile** [comment]
Related to this, I'm seeing it includes Access teams in the retrieved list. So this is what's putting my list over 5000 and cutting off actual Owner teams.

**Comment by carfup** [comment]
Thanks for your feedback as wel ovinophile, will include the filter of teams as well !

I will keep you updated when i find some times to fix these 2 issues !

**Comment by SrinivasPodili** [comment]
Hi,
Even I am facing the issue "Users list is not being loaded completely". Need help on fixing the issue.

**Comment by carfup** [comment]
Hello guys,
First of all, sorry for the delay here ...
@seanmcne  : i updated the code to retrieve all users properly
@ovinophile  : i updated the code to retrieve only the owner teams
@SrinivasPodili : is this a generic error ? I never saw it, and it's not a custom one, do you have any screenshot or log file here ?

Thanks,
Clément

**Comment by SrinivasPodili** [comment]
@carfup: There is no error on UI. My issue is same as that of seanmcne reported. Plugin is not showing full Users list. You have mentioned that code fix was completed. Is the code available for public release?

**Comment by SrinivasPodili** [comment]
@carfup: There is no error on UI. My issue is same as that of seanmcne reported. Plugin is not showing full Users list. You have mentioned that code fix was completed. Is the code available for public release?

**Comment by carfup** [comment]
Hi,
I will publish the release with the fix on monday.
Will update the issue to let you know !

**Comment by carfup** [comment]
Hi,
This is now fixed with the published version 1.2019.9.9 on the XrmToolBox Plugin Store
