### ISSUE TITLE
Plugin hangs when clicking Load CRM Users

### ISSUE THREAD

**Issue by ashwinravi** [carfup/XTBPlugins.PersonalViewsMigration#28]
Our CRM org has about 20k+ users and when I click 'Load CRM Users' on this plugin, the plugin hangs and as a result, I have to restart XrmToolBox. I noticed that you recently fixed the issue to load more than 5k users but it doesn't seem to be working for me. Any ideas?

**Comment by carfup** [comment]
Hello,
Would it be possible to provide me an account on your org in order to test that ?
I don't have org on my side with that many users ...
I'm reachable via : https://www.linkedin.com/in/clemolivier/
Cheers

**Comment by ashwinravi** [comment]
Hi Clement, I may not be able to share an account on my org but I can definitely work with you and help troubleshoot on a call and screen share. I can do later next week sometime. Lets coordinate on Linkedin and work out a time. Sound good?

**Comment by carfup** [comment]
Hello,
I'm sorry for the very late answer here but I fixed the problem and this will be pushed with the next release.
Soon enough I hope ! :)

**Comment by carfup** [comment]
Hello @ashwinravi 

This is now fixed with the latest release #34 !

Enjoy !
