### ISSUE TITLE
Error when clicking Load users/teams " 'Team' entity doesn't contain attribute with Name =  'teamtype'. "

### ISSUE THREAD

**Issue by arouse-rhc** [carfup/XTBPlugins.PersonalViewsMigration#29]
Using CRM 2011 Rollup 14. This has been working fine until the most recent update.

Error when clicking Load users/teams " 'Team' entity doesn't contain attribute with Name =  'teamtype'. "
![XrmToolBox_FoPep6gyHJ](https://user-images.githubusercontent.com/8751710/67213947-e3220600-f3ec-11e9-825d-b71478f38b40.png)

**Comment by carfup** [comment]
This is fixed with the latest version.
