### ISSUE TITLE
Getting "You have reached the maximum number of non-interactive users"

### ISSUE THREAD

**Issue by nsunkara-vijaya** [carfup/XTBPlugins.PersonalViewsMigration#35]
Hi Team,

I am using this plugin to share dashboards to different users.

While selecting "DashBoards" by checking checkbox I am getting following error.

"You have reached the maximum number of non-interactive users/"

Please help me

Regards,
Babu

**Comment by carfup** [comment]
Hello,

Long time to fix that, I'm so sorry ...
Actually the limitation is pushed by MS, and is 7 per environment.
If the user you want to check the data from is disabled you need to have at least one seat available.

I've updated the package the new version will be available in an hour in the XrmToolBox Tools librairy
