### ISSUE TITLE
Delete deleted user shared view

### ISSUE THREAD

**Issue by ncc0706** [carfup/XTBPlugins.PersonalViewsMigration#36]
If a user has been deleted, can he still delete his shared view?

**Comment by carfup** [comment]
Hello @ncc0706,
Yes you can until 30 days after the deletion as far as I remember. 
The user is in the "recycle bin" during 30 days before the actual real deletion from the ad and then you want do anything unfortunately.
Regards

**Comment by carfup** [comment]
Sounds fair as answer ? 
I'm closing the issue, feel free to reopen it if necessary.
