### ISSUE TITLE
First Item in List being removed when clicking 'Delete selected sharings' in Manage item Sharing window

### ISSUE THREAD

**Issue by adamrouse** [carfup/XTBPlugins.PersonalViewsMigration#37]
MSCRM Version: On Prem - CRM 2011 5.0.9
**Steps to reproduce:**
1. Select a shared view.
2. Click Manage item Sharings button.
3. Place a checkmark next to second last user on list.
4. Press Delete selected sharings.

**Current result:**
Item that did not have a checkmark next to it at the top of the list was removed.
![FirstImage](https://user-images.githubusercontent.com/52517760/140189535-5852c359-9a91-4260-9088-f0a3615fde3e.png)
![SecondImage](https://user-images.githubusercontent.com/52517760/140189536-34bd132b-4218-4f0b-9e61-8b2d43053a74.png)

**Comment by carfup** [comment]
Hello @adamrouse ,

Thanks for bringing this up. I can reproduce this too so I'll work on a fix as soon as I can.

Regards,

**Comment by adamrouse** [comment]
Hi @carfup 
Thank you so much for checking, I'd be happy to test whenever its ready.

**Comment by carfup** [comment]
Hello @adamrouse ,

I'm so sorry for the delay here.
I fixed the issue and published the new version (1.2022.1.12), it should be available pretty soon within the Tools library of XrmToolBox.

Cheers

**Comment by adamrouse** [comment]
Thank you so much! I'll retest it as soon as I see it in the Library and post an update.

**Comment by adamrouse** [comment]
Hi @carfup,
I tested this successfully. Thanks again for looking into this and updating it.
