### ISSUE TITLE
Can't convert to system dashboard

### ISSUE THREAD

**Issue by greensweater** [carfup/XTBPlugins.PersonalViewsMigration#42]
Error when selecting a user dashboard and clicking "Convert to System" button: 

The label "Tab", id: '[guid]' already exists. Supply unique labelid values.

Adding a detail here that is probably relevant: the user dashboard I am trying to convert was originally edited from a system dashboard.

**Comment by carfup** [comment]
Thanks a lot @greensweater for your contribution.
Sorry for the late reply, was on holidays !

I'll publish your update later today or tomorrow.
I keep you update.

**Comment by carfup** [comment]
Release is deployed and available in the Tool library !
